---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: starkandwayne/concourse-go
    tag: '1.16'

inputs:
  - name: git-ci
  - name: git
  - name: cf-deployment

outputs:
  - name: git

run:
  path: git-ci/ci/tasks/get-latest-cf-deployment/task
